show databases;
use 19pw33;

CREATE TABLE IF NOT EXISTS Employee
(
    ENO    BIGINT,
    FNAME  VARCHAR(50) NOT NULL,
    LNAME  VARCHAR(50) NOT NULL,
    DESIG  VARCHAR(50),
    MGR    BIGINT,
    DOB    DATE,
    HDATE  DATE,
    SALARY NUMERIC(8, 2),
    COMM   NUMERIC(8, 2),
    PRIMARY KEY (ENO),
    FOREIGN KEY (MGR) REFERENCES Employee (ENO),
    CONSTRAINT DOB_Check CHECK ( YEAR(DOB) <= 1980 ),
    CONSTRAINT Salary_Check CHECK ( SALARY BETWEEN 20000 AND 100000 )
);


INSERT INTO Employee
VALUES (101, 'Janson', 'Hass', 'President', NULL, STR_TO_DATE('12/09/1973', '%d/%m/%Y'),
        STR_TO_DATE('12/01/2003', '%d/%m/%Y'), 87500.00, NULL),
       (110, 'James', 'Thompson', 'Manager', 101, STR_TO_DATE('06/01/1973', '%d/%m/%Y'),
        STR_TO_DATE('25/02/2008', '%d/%m/%Y'), 52950.00, NULL),
       (115, 'Celia', 'Geyer', 'Manager', 101, STR_TO_DATE('07/09/1972', '%d/%m/%Y'),
        STR_TO_DATE('17/09/2007', '%d/%m/%Y'), 46850.00, 22530.00),
       (117, 'Robert', 'Stern', 'Manager', 101, STR_TO_DATE('04/02/1972', '%d/%m/%Y'),
        STR_TO_DATE('15/03/2006', '%d/%m/%Y'), 49900.00, 20555.00),
       (135, 'Linda', 'Pulaski', 'Salesman', 110, STR_TO_DATE('29/08/1968', '%d/%m/%Y'),
        STR_TO_DATE('19/09/2007', '%d/%m/%Y'), 21250.00, 14500.00),
       (142, 'David', 'Henderson', 'Salesman', 110, STR_TO_DATE('02/02/1970', '%d/%m/%Y'),
        STR_TO_DATE('23/03/2006', '%d/%m/%Y'), 21700.00, 12400.00),
       (167, 'Martin', 'Spenser', 'Salesman', 110, STR_TO_DATE('09/02/1971', '%d/%m/%Y'),
        STR_TO_DATE('28/07/2005', '%d/%m/%Y'), 27000.00, 16600.00),
       (172, 'Smith', 'Nicholls', 'Clerk', 110, STR_TO_DATE('12/03/1965', '%d/%m/%Y'),
        STR_TO_DATE('26/04/2003', '%d/%m/%Y'), 21850.00, NULL),
       (154, 'Larry', 'Adamson', 'Salesman', 110, STR_TO_DATE('02/02/1974', '%d/%m/%Y'),
        STR_TO_DATE('18/02/2004', '%d/%m/%Y'), 22250.00, 17000.00),
       (179, 'Mathews', 'Pinka', 'Analyst Manager', 117, STR_TO_DATE('08/01/1975', '%d/%m/%Y'),
        STR_TO_DATE('23/04/2008', '%d/%m/%Y'), 35000.00, NULL),
       (183, 'Sally', 'Brown', 'Clerk', 179, STR_TO_DATE('29/08/1968', '%d/%m/%Y'),
        STR_TO_DATE('14/07/2008', '%d/%m/%Y'), 21250.00, NULL),
       (190, 'Christine', 'Jones', 'Analyst Manager', 117, STR_TO_DATE('13/09/1968', '%d/%m/%Y'),
        STR_TO_DATE('05/09/2005', '%d/%m/%Y'), 34000.00, NULL),
       (199, 'Michael', 'Parker', 'Clerk', 190, STR_TO_DATE('07/02/1971', '%d/%m/%Y'),
        STR_TO_DATE('17/03/2004', '%d/%m/%Y'), 21600.00, NULL),
       (200, 'John', 'Mehta', 'Clerk', 115, STR_TO_DATE('02/03/1975', '%d/%m/%Y'),
        STR_TO_DATE('12/02/2006', '%d/%m/%Y'), 21350.00, NULL),
       (137, 'Bruce', 'Wong', 'Salesman', 110, STR_TO_DATE('12/12/1976', '%d/%m/%Y'),
        STR_TO_DATE('18/10/2005', '%d/%m/%Y'), 22250.00, 13000.00);

SELECT *
FROM Employee;
DROP TABLE Employee;

# 1
SELECT *
FROM Employee
WHERE TIMESTAMPDIFF(YEAR, DOB, CURRENT_TIMESTAMP) <
      (SELECT TIMESTAMPDIFF(year, DOB, current_timestamp) FROM Employee WHERE ENO = 167);

# 2
SELECT FNAME, LNAME
FROM Employee
WHERE TIMESTAMPDIFF(YEAR, DOB, CURRENT_TIMESTAMP);

# 3
SELECT *
FROM Employee
WHERE LNAME REGEXP 'er';

# 4
SELECT CONCAT(FNAME, ' ', LNAME) AS NAME
FROM Employee
WHERE FNAME REGEXP '^[MJ]';

# 5
SELECT FNAME, LNAME, SALARY
FROM Employee
WHERE DESIG IN ('Analyst Manager', 'Manager');

# 6
SELECT *
FROM Employee
WHERE TIMESTAMPDIFF(YEAR, DOB, CURRENT_TIMESTAMP) =
      (SELECT DISTINCT MAX(TIMESTAMPDIFF(YEAR, DOB, CURRENT_TIMESTAMP)) FROM Employee);

# 7
SELECT *
FROM Employee
WHERE DESIG NOT IN ('Manager', 'Analyst Manager');

# 8
SELECT *
FROM Employee
WHERE SALARY > 35000
  AND YEAR(DOB) BETWEEN 1966 AND 1976;

# 9
SELECT ENO, FNAME, LNAME, DESIG, SALARY
FROM Employee
WHERE SALARY >= 35000
  AND DESIG IN ('Manager', 'Analyst Manager');

# 10
SELECT ENO, FNAME, LNAME, DESIG, SALARY
FROM Employee
WHERE Commission >= 15000
  AND DESIG IN ('Salesman', 'Manager');

# 11
SELECT DESIG, COUNT(*) AS COUNT
FROM Employee
GROUP BY DESIG;

# 12
SELECT ENO, LNAME, SALARY
FROM Employee
WHERE LNAME IN ('Thompson', 'Spenser', 'Geyer', 'Brown', 'Jones');

# 13
SELECT YEAR(HDATE), COUNT(*) AS Count
FROM Employee
GROUP BY YEAR(HDATE);

# 14
SELECT ENO, LNAME, SALARY, TIMESTAMPDIFF(YEAR, DOB, CURRENT_TIMESTAMP) AS Age
FROM Employee
WHERE TIMESTAMPDIFF(YEAR, DOB, CURRENT_TIMESTAMP) BETWEEN 30 AND 40;

# 15
SELECT FNAME
FROM Employee
WHERE MGR IN (SELECT ENO FROM Employee WHERE FNAME IN ('James', 'Robert', 'Celia'));

# 16
SELECT CONCAT(FNAME, ', ', LNAME, ', ', DESIG)
FROM Employee;

# 17
SELECT MIN(TIMESTAMPDIFF(YEAR, DOB, CURRENT_TIMESTAMP)) AS AGE
FROM Employee
WHERE COMM IS NOT NULL;

# 18
SELECT CONCAT('Dear, ', FNAME, ' you were born on ', DATE_FORMAT(DOB, '%d, %W-%M-%Y')) AS Description
FROM Employee;

# 19
SELECT *
FROM Employee
WHERE (DESIG, SALARY) IN (SELECT DESIG, MAX(SALARY) AS SALARY FROM Employee GROUP BY DESIG);

# 20
SELECT ENO, FNAME, SALARY
FROM Employee
WHERE MONTHNAME(DOB) IN ('January', 'February', 'August');

# 21
SELECT FNAME, SALARY, COALESCE(COMM, 0) AS COMMISSION, SALARY + COALESCE(COMM, 0) AS REMUNATION
FROM Employee;

# 22
SELECT FNAME, SALARY, COALESCE(COMM, 0) AS COMMISSION, SALARY + COALESCE(COMM, 0) AS REMUNATION
FROM Employee;

# 23
SELECT FNAME, DESIG
FROM Employee
WHERE (DESIG, TIMESTAMPDIFF(YEAR, HDATE, CURRENT_TIMESTAMP)) IN
      (SELECT DESIG, MAX(TIMESTAMPDIFF(YEAR, HDATE, CURRENT_TIMESTAMP)) AS NAME FROM Employee GROUP BY DESIG);

# 24
SELECT *
FROM Employee
WHERE DESIG = 'Manager'
  AND SALARY > 40000
  AND YEAR(DOB) < 1973;

# 25
SELECT *
FROM Employee
WHERE COMM IS NULL
  AND SALARY BETWEEN 25000 AND 35000;

# 26
SELECT *
FROM Employee
WHERE MONTH(DOB) = MONTH(HDATE);

# 27
SELECT ENO, FNAME, DATE_FORMAT(HDATE, '%M %d,%Y') AS HIRE_DATE
FROM Employee;

# 28
SELECT ENO,
       CONCAT(FNAME, ' ', LNAME)                       AS NAME,
       DESIG,
       HDATE,
       TIMESTAMPDIFF(YEAR, HDATE, CURRENT_TIMESTAMP()) AS EXPERIENCE
FROM Employee
WHERE ENO IN (SELECT DISTINCT MGR FROM Employee);

# 29
SELECT ENO, CONCAT(FNAME, ' ', LNAME) AS NAME, SALARY
FROM Employee
WHERE TIMESTAMPDIFF(YEAR, HDATE, CURRENT_TIMESTAMP()) > 5
  AND DESIG IN ('Manager', 'Analyst Manager')
  AND COMM IS NULL
ORDER BY ENO;

# 30
SELECT *
FROM Employee
WHERE YEAR(HDATE) < (SELECT YEAR(HDATE) FROM Employee WHERE FNAME = 'Martin');

# 31
SELECT FNAME
FROM Employee
WHERE SALARY = (SELECT SALARY FROM Employee WHERE FNAME = 'Larry')
  AND FNAME != 'Larry';

# 32
SELECT CONCAT(FNAME, ' ', LNAME) AS NAME
FROM Employee
WHERE DESIG = (SELECT DESIG FROM Employee WHERE FNAME = 'James') AND FNAME != 'James'
   OR SALARY > (SELECT SALARY FROM Employee WHERE FNAME = 'Celia');

# 33
SELECT *
FROM Employee
WHERE SALARY > (SELECT AVG(SALARY) FROM Employee);

# 34
SELECT *
FROM Employee
WHERE DESIG = 'Salesman'
ORDER BY YEAR(HDATE) DESC
LIMIT 1;

# 35
SELECT *
FROM Employee
WHERE YEAR(HDATE) < (SELECT YEAR(HDATE) FROM Employee WHERE MGR = 110 ORDER BY YEAR(HDATE) DESC LIMIT 1);

# 36
SELECT *
FROM Employee
ORDER BY TIMESTAMPDIFF(YEAR, DOB, 1991) DESC
LIMIT 1;

# 37
SELECT CONCAT(FNAME, ' ', LNAME) AS NAME
FROM Employee
WHERE SALARY >= (SELECT (MAX(SALARY) + MIN(SALARY)) / 2 FROM Employee);

# 38
SELECT CONCAT(FNAME, ' ', LNAME) AS NAME
FROM Employee
ORDER BY (SALARY + COALESCE(COMM, 0))
LIMIT 5;

# 39
SELECT CONCAT(FNAME, ' ', LNAME) AS NAME, SALARY, COMM
FROM Employee
ORDER BY (SALARY + COALESCE(COMM, 0)) DESC
LIMIT 1;

# 40
SELECT CONCAT(FNAME, ' ', LNAME) AS NAME
FROM Employee
WHERE DAY(HDATE) IN (SELECT DAY(HDATE) FROM Employee GROUP BY DAY(HDATE) HAVING COUNT(*) > 1);

# 41
SELECT ENO
FROM Employee
WHERE MGR IS NULL;

# 42
SELECT ENO
FROM Employee
WHERE ENO = (SELECT MGR FROM Employee GROUP BY MGR ORDER BY COUNT(*) DESC LIMIT 1);

# 43
SELECT *
FROM Employee
WHERE (DESIG, HDATE) IN (SELECT DESIG, MAX(HDATE) FROM Employee GROUP BY DESIG ORDER BY MAX(HDATE));

# 44
SELECT FNAME, DESIG
FROM Employee
WHERE COMM IS NOT NULL
  AND SALARY = (SELECT MAX(SALARY) FROM Employee WHERE COMM IS NOT NULL);

# 45
SELECT *
FROM Employee
WHERE SALARY IN (SELECT SALARY FROM Employee GROUP BY SALARY HAVING COUNT(*) > 1);

# 46
SELECT AVG(SALARY), DESIG
FROM Employee
WHERE DESIG != 'President'
GROUP BY DESIG
ORDER BY AVG(SALARY) DESC
LIMIT 1;

# 47
SELECT *
FROM Employee
WHERE ENO NOT IN (SELECT DISTINCT MGR FROM Employee WHERE MGR IS NOT NULL);

# 48
SELECT SUM((SALARY + COALESCE(COMM, 0))) AS REMUNERATION
FROM Employee
WHERE MGR = 110;

# 49
UPDATE Employee
SET COMM = COMM + (0.1 * SALARY)
WHERE MONTH(DOB) = MONTH(CURRENT_TIMESTAMP);

# 50
DELETE
FROM Employee
WHERE SALARY > 40000
  AND DESIG NOT IN ('President', 'Manager');